{% set name = "algopy" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24b89938605d063240196f9d0da4f3e87ec7fc68a3f1f655c862178be52b59c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - scipy

test:
  imports:
    - algopy
    - algopy.fft
    - algopy.linalg
    - algopy.nthderiv
    - algopy.special
    - algopy.tests
    - algopy.tracer
    - algopy.tracer.tests
    - algopy.tracer.tests.test_output
    - algopy.utpm
    - algopy.utpm.tests

about:
  home: http://packages.python.org/algopy
  license: BSD
  license_family: BSD
  license_file: README.rst
  summary: 'ALGOPY: Taylor Arithmetic Computation and Algorithmic Differentiation'
  description: |
    ALGOPY is a tool for Algorithmic Differentiation (AD) and Taylor polynomial
    approximations.  ALGOPY makes it possible to perform computations on scalar
    and polynomial matrices.  It is designed to be as compatible to numpy as
    possible. I.e. views, broadcasting and most functions of numpy can be
    performed on polynomial matrices. Exampels are dot,trace,qr,solve,
    inv,eigh. The reverse mode of AD is also supported by a simple code
    evaluation tracer.
  doc_url: http://pythonhosted.org/algopy
  dev_url: https://github.com/b45ch1/algopy

extra:
  recipe-maintainers:
    - nehaljwani
