travis:
  secure:
    BINSTAR_TOKEN: fJnIQACiL3ZlDWIJAniYRvkQlr+NXsJD2xaWidLlshPd9tJMrqMtIb2/ijnIY9V0v+LWoyFDWC7uukFf1iTPR8tmNNZzUz95NdDTm5ZAz40Y/XD4LiRKvuq7HTV7BMNG4jSC9fQu1SHMFi37g5GiKMmsbKmhMhDrsFy/1/ZWKLhy7HTrtgaQjGZAeqyCqAXxBjypMDLaNLpZVHkylrqhjSyjLiny47C459qnDFfcYGBFiSzZglQhlIcic8Fa9ixnDAcgKXUHB7z1O1oXGKFBPiKAUqr4w8gVSXQ0Yz707J8VB1qSq0S2kpubKZcJmE3xKPIWnYTjzgP6KU4tuxQ1Ls9psNKShNlWfnVpAqCr0GmR+cIrAStgTCA1pS+8JDKRdCGgVH9SMmty9F4n7M+lkaa/gM29j3+HDpG5ifaBecTcC6crsMiR/nW0sq81i/uXbacxkog92HKuPOXsKmnk/O844cdGPqTnX1dpCllsDbuSeCHa3JNYQWhZy8ciBk3wMAaT6q+WUuhjnzOingAjLsvQqigNA17+4Ld9JTUfDWRLmI8RqTKCAFdQHlyhWn7u5cgsUYaey/ahSqakaTfyVLhP8J/PPMRkVgTXGX2WE5eWu5y/Liooa4kTfmAMMsxYJ3PwxzfIc2nFZFMGR0+owEhyF4d1z8yKje9UvxvqodI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
