travis:
  secure:
    BINSTAR_TOKEN: CclXbTKp2TBCX4mdvy3xQ/tDcVYmDOr4HHZ3+ymPI7FoNnzk+XQURXZ6Q353G5J9LHeRc4PLPFI1a+2eqqZHykOP24y2FABJURmYFFu+czpYEWxBR9y0j7+ByeI9CuRZyNvlGb0HHWPGxgdJIEnKh8Yo8dt8XMA6uku5saktHoEJXuvGag5QalI9Mu6H1Vw8U6pUO3n4Ik/ddqOpfJRlwTxTI+Jc6kUUZxzbDr46FSfdkZfotgQhjx8io4yzJFB0s+AhvYP5NR2x/Hn8abxwNuJ+V8ZShTHp8pnCOCYwnwQAtov2Cax8JGG6aker8oYLhaCPM1/6bDk8EQz+m/MKbLCtIueMHLiOP+WP69C41wTVjP992lSAVa+sweSKvWXKLYrIZPiMd7gfMzZnsh/hDp+cudhyorvZmDsaGCeqnuvX/Bsx5ECpm8PZZIY96qXXbbGeSvoSyX8yisry/Zoe2qoxDYt9pFpB5XXNs9KxaHdTCuypX5xJA9fR9Y2XgXlbLEQ+vGOhxB6FHhF/2/SRv+3C8XMA46fqX3p9aSM/AO+2ERCcrLtMB0RijtdscLv8yEg/66pi8IcSf/gL92T7wqcfabV9+fYRtwYlnflVO9Um0wVI6Ze3svywaJgAjC6mbGXem9IgxE1+NAH1VKOqfXohyTdz+69tpareZfas814=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
